name: Feature Request
description: Suggest a new feature for Caesium Image Compressor v3
title: "[Feature]: "
labels: ["enhancement", "v3"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to have...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: I've also thought about...
    validations:
      required: false

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of the application does this feature relate to?
      options:
        - Image Compression
        - Batch Processing
        - User Interface
        - Settings/Configuration
        - File Management
        - Performance
        - Export/Import
        - Metadata Handling
        - Image Resizing
        - Preview/Comparison
        - Other
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how this feature would be used and who would benefit from it.
      placeholder: This would help users who...
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: |
        If applicable, add mockups, screenshots, or examples to help illustrate your idea.
        You can drag and drop images here.
      placeholder: Paste or drag mockups/examples here
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request.
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I have checked the v3 discussion thread for similar suggestions
          required: false
        - label: This feature aligns with the goals of Caesium Image Compressor
          required: true
