name: Question/Support
description: Ask a question or get help
title: "[Question] "
labels: [ "question", "v3" ]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about using Caesium? We're here to help!
        
        **Note:** For general discussion about v3, consider using the [discussion thread](https://github.com/Lymphatus/caesium-image-compressor/issues/334).

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: I would like to know how to...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation/Setup
        - Usage/How-to
        - Configuration/Settings
        - Image Formats
        - Batch Processing
        - Performance
        - Build from Source
        - Troubleshooting
        - Other
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Please provide any relevant context or what you've already tried.
      placeholder: I've tried... but...
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Caesium Version
      description: What version of Caesium are you using?
      placeholder: "3.0.0-alpha.0"
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 10
        - Windows 11
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Linux (Other)
        - Other
    validations:
      required: false

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What version of your operating system?
      placeholder: "e.g., Windows 11 23H2, macOS 14.5, Ubuntu 24.04"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your question.
        You can drag and drop images here.
      placeholder: Paste or drag screenshots here
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for similar questions
          required: true
