[package]
authors = ["Matteo Paonessa"]
description = "Caesium is an image compression software that helps you store, send and share digital pictures"
edition = "2021"
name = "caesium-image-compressor"
version = "3.0.0-alpha.2"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "caesium_image_compressor_lib"

[build-dependencies]
tauri-build = {version = "2", features = []}

[dependencies]
base16ct = {version = "0.3", features = ["alloc"]}
file-format = "0.28.0"
imagesize = "0.14"
indexmap = "2.11"
kamadak-exif = "0.6"
libcaesium = "0.20"
log = "0.4"
open = "5.3"
rayon = "1.11"
regex = "1.11.2"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_repr = "0.1"
sha2 = "0.10"
system_shutdown = "4"
tauri = {version = "2", features = ["protocol-asset"]}
tauri-plugin-dialog = "2.4"
tauri-plugin-fs = "2"
tauri-plugin-log = "2"
tauri-plugin-notification = "2"
tauri-plugin-opener = "2"
tauri-plugin-os = "2"
tauri-plugin-process = "2"
tauri-plugin-store = "2.4"
tauri-plugin-window-state = "2"
thiserror = "2.0.16"
trash = "5.2"
walkdir = "2.5"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2"
